### ISSUE TITLE
Do a new release?

### ISSUE THREAD

**Issue by rbtcollins** [libpnet/netmap_sys#12]
There are useful things like 9d719c9ce1006edce6ed9c5da28da5dd0d967062 in master but not released.

**Comment by polachok** [comment]
That would be nice, I wouldn't have to depend on git rev in [netmap-rs](https://github.com/polachok/netmap-rs)

**Comment by mrmonday** [comment]
@polachok I've given you write access to the repository, and publish access to the netmap_sys crate on crates.io.

For a new release, you just need to bump the version number in `Cargo.toml`, and `README.md`.

I'd appreciate it if you could make pull requests for changes so that the tests run before things get into master, and it also means if you're making bigger changes there's time for some code review.
